site_name: Images
site_description: An image processing library for Julia
site_author: Tim Holy
repo_url: https://github.com/timholy/Images.jl.git
repo_name: GitHub
docs_dir: docs/build
use_directory_urls: true
theme: mkdocs

pages:
- Home: home.md
- User Guide:
  - Aims: aims.md
  - Core Concepts: core.md
  - Overlays: overlays.md
- Function Reference: function_reference.md
- About:
#  - Contributing: contributing.md
  - License: LICENSE.md
#  - Release Notes: NEWS.md
